import type { ImageRecord } from "@/lib/storage/types";

export function buildFixedReplicatePrompt(sourceImage: ImageRecord): string {
  return [
    "出力は1枚の完成イラストにする。2分割、左右並列、コラージュ、比較画像、複数コマのような表現にはしない。",
    "画面の左右端に別画像の断片、余白、境界線、分割線、不要な追加物を作らない。1枚の自然な背景イラストとして仕上げる。",
    "優先順位は、1) 背景は入力画像2の構図と配置を維持する、2) 犬は入力画像1の特徴を保ちつつ完全にアニメイラストとして描き直す、の順とする。",
    "入力画像2の会場風景を画面全体の背景として採用し、背景の屋台、のぼり、テント、机、建物、通路などの配置や構図は極力変えない。",
    "背景画像2のカメラアングル、遠近感、レイアウト、主要オブジェクトの位置関係をできるだけ維持し、背景は入力画像2をそのままアニメイラスト化したように見せる。",
    "入力画像1の犬だけを、背景画像2の会場中央にある石畳の通路の上に配置する。",
    "入力画像1に複数の犬がいた場合、全ての犬を配置する。",
    "複数の犬がいる場合は、犬たちを1つのグループとして、黄色ののぼりの右側かつ緑のテントの前に見える石畳の通路上に自然に並べる。",
    "複数の犬を上下に分けたり、別領域、別レイヤー、別パネルのように分離して描かない。",
    "入力画像1から使う情報は犬本体の特徴だけに限定する。草原、空、地面、遠景、元写真の背景情報は一切使わない。",
    "入力画像1の背景を参照したり再現したりしない。背景は必ず入力画像2のみを使う。",
    "犬の毛色、体型、耳の形、顔立ち、向き、表情、ポーズの特徴は保つ。ただし写真の質感、毛の細かすぎる実写感、レンズ感、切り抜き写真のような見え方は残さない。",
    "犬のリードは描画しない。",
    "犬は背景に貼り付けた写真素材ではなく、背景世界の中に存在するアニメキャラクターとして完全に描き直す。",
    "Keep the dog's identity, colors, face, ears, pose, and body proportions, but do not preserve photographic texture.",
    "Fully redraw the dog as an illustrated anime character integrated into the scene, not as a pasted photo cutout.",
    "Avoid photorealistic fur, camera-like detail, realistic lighting, and photo-composite appearance.",
    "犬は背景イラストの雰囲気になじむ、可愛く親しみやすい、手描きアニメイラスト風にする。硬すぎず、やさしく魅力的な表情にする。",
    "犬はフォトリアルにしない。実写風、写真合成風、毛並みの細かすぎる写実表現、切り抜き素材のような見え方を避ける。",
    "犬ははっきりした輪郭線、整理された毛束、少し大きめで可愛い目、やわらかい陰影でアニメキャラクターのように描く。",
    "Render the dog with clean line art, simplified fur shapes, soft cel shading, and cute expressive eyes.",
    "犬の見た目は背景よりも一段強くスタイライズし、可愛いアニメマスコットのような印象にする。",
    "犬は空中に浮かせない。必ず会場の通路や地面の上に接地させ、足元が床面に触れている状態にする。",
    "犬の足元には自然な接地影を描き、背景の遠近感と光の向きに合わせる。",
    "犬は画面の下半分に配置し、空や建物の屋根の上、画面上部には置かない。",
    "犬は会場内で自然な実寸スケールにし、人や屋台に対して極端に大きくしない。",
    "犬は通路や広場の手前側に自然に配置し、黄色ののぼり、緑のテント、机の前にある石畳の通路上に立たせる。",
    "Do not place the dog in the sky, floating in the air, or on rooftops. The dog must stand on the ground.",
    "Place the dog group on the central stone-paved walkway of the venue, to the right of the yellow banner and in front of the green tent.",
    "Keep all dogs together as one group standing on the same ground plane on that walkway.",
    "Do not separate the dogs into a different panel, layer, isolated area, or top section of the image.",
    "Do not split the image into top and bottom sections. Integrate all dogs naturally into the same background scene.",
    "全体は鮮やかで統一感のあるアニメイラスト風にするが、背景会場の見え方は入力画像2にできるだけ忠実にする。",
    "背景を作り直すのではなく、背景は入力画像2をベースにし、その上で犬も背景の世界観に合わせて描き直した1枚絵にする。",
    `元画像ファイル名: ${sourceImage.storedName}`,
  ].join(" ");
}
